#include "molshredder/gui/action_catalog.hpp"

#include <algorithm>
#include <array>
#include <cctype>
#include <set>
#include <tuple>
#include <utility>

namespace molshredder::gui {
namespace {

constexpr ActionSurfaces kMenuToolbarPalette =
    surface_mask(ActionSurface::menu) |
    surface_mask(ActionSurface::toolbar) |
    surface_mask(ActionSurface::command_palette);
constexpr ActionSurfaces kMenuPalette = surface_mask(ActionSurface::menu) |
                                        surface_mask(ActionSurface::command_palette);
constexpr ActionSurfaces kMenuPanelPalette =
    kMenuPalette | surface_mask(ActionSurface::panel);
constexpr ActionSurfaces kMenuToolbarPanelPalette =
    kMenuToolbarPalette | surface_mask(ActionSurface::panel);
constexpr ActionSurfaces kMenuContextPalette =
    kMenuPalette | surface_mask(ActionSurface::context_menu);
constexpr ActionSurfaces kMenuPanelContextPalette =
    kMenuPanelPalette | surface_mask(ActionSurface::context_menu);

constexpr std::array<ActionMetadata, 36U> kActions{{
    {.id = "file.open",
     .command_name = "load",
     .menu = "file",
     .label_source = "Open",
     .status_source =
         "Open one or more molecular structures or scalar volumes",
     .error_source = "Molecular data could not be opened",
     .keywords_source = "open import load structure volume",
     .unavailable_source = "",
     .shortcut = "standard.open",
     .help_target = "desktop.multi-file-open",
     .parameter_group = "file.open",
     .order = 10U,
     .surfaces = kMenuToolbarPalette,
     .requirements = 0U,
     .checkable = false},
    {.id = "file.save",
     .command_name = "save",
     .menu = "file",
     .label_source = "Save",
     .status_source = "Save the active molecular object's coordinates",
     .error_source = "The active molecular object could not be saved",
     .keywords_source = "save export write coordinates",
     .unavailable_source = "Open a molecular structure before saving",
     .shortcut = "standard.save",
     .help_target = "desktop.save",
     .parameter_group = "file.save",
     .order = 20U,
     .surfaces = kMenuToolbarPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "file.open-session",
     .command_name = "session load",
     .menu = "file",
     .label_source = "Open Session…",
     .status_source = "Open a versioned MolShredder session",
     .error_source = "The session could not be opened",
     .keywords_source = "open load session recovery relink",
     .unavailable_source = "",
     .shortcut = "",
     .help_target = "session.open",
     .parameter_group = "session.load",
     .order = 30U,
     .surfaces = kMenuPanelPalette,
     .requirements = 0U,
     .checkable = false},
    {.id = "file.save-session",
     .command_name = "session save",
     .menu = "file",
     .label_source = "Save Session…",
     .status_source = "Save the full viewer state and operation journal",
     .error_source = "The session could not be saved",
     .keywords_source = "save session autosave workspace scene movie",
     .unavailable_source = "Open or build a workspace before saving a session",
     .shortcut = "",
     .help_target = "session.save",
     .parameter_group = "session.save",
     .order = 40U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "edit.undo",
     .command_name = "edit undo",
     .menu = "edit",
     .label_source = "Undo Molecular Edit",
     .status_source = "Undo the latest molecular edit",
     .error_source = "The molecular edit could not be undone",
     .keywords_source = "edit undo molecule coordinate topology builder history rollback",
     .unavailable_source = "Open a molecular structure before undoing an edit",
     .shortcut = "standard.undo",
     .help_target = "editing.undo-redo",
     .parameter_group = "edit.history",
     .order = 10U,
     .surfaces = kMenuPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "edit.redo",
     .command_name = "edit redo",
     .menu = "edit",
     .label_source = "Redo Molecular Edit",
     .status_source = "Redo the latest undone molecular edit",
     .error_source = "The molecular edit could not be redone",
     .keywords_source = "edit redo molecule coordinate topology builder history replay",
     .unavailable_source = "Open a molecular structure before redoing an edit",
     .shortcut = "standard.redo",
     .help_target = "editing.undo-redo",
     .parameter_group = "edit.history",
     .order = 20U,
     .surfaces = kMenuPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "edit.atom-position",
     .command_name = "edit atom-position",
     .menu = "edit",
     .label_source = "Atom Coordinates…",
     .status_source = "Open the stable-ID atom coordinate editor",
     .error_source = "The atom coordinate editor could not be opened",
     .keywords_source = "edit atom coordinates position move builder",
     .unavailable_source = "Open a static molecular structure before editing coordinates",
     .shortcut = "",
     .help_target = "editing.atom-position",
     .parameter_group = "edit.atom-position",
     .order = 30U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "edit.atom-properties",
     .command_name = "edit atom-properties",
     .menu = "edit",
     .label_source = "Atom Properties…",
     .status_source = "Edit stable-ID atom identity and charge properties",
     .error_source = "The atom properties could not be edited",
     .keywords_source = "edit atom name element atomic number charge",
     .unavailable_source = "Open a static molecular structure before editing atom properties",
     .shortcut = "",
     .help_target = "editing.atom-properties",
     .parameter_group = "edit.atom-properties",
     .order = 40U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "edit.residue-properties",
     .command_name = "edit residue-properties",
     .menu = "edit",
     .label_source = "Residue Properties…",
     .status_source = "Edit the residue identified by a stable atom ID",
     .error_source = "The residue properties could not be edited",
     .keywords_source = "edit residue name chain sequence number",
     .unavailable_source = "Open a static molecular structure before editing residue properties",
     .shortcut = "",
     .help_target = "editing.residue-properties",
     .parameter_group = "edit.residue-properties",
     .order = 50U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "edit.bond-order",
     .command_name = "edit bond-order",
     .menu = "edit",
     .label_source = "Bond Order…",
     .status_source = "Edit stable-ID bond order semantics",
     .error_source = "The bond order could not be edited",
     .keywords_source = "edit bond order single double triple aromatic amide",
     .unavailable_source = "Open a static molecular structure before editing bond order",
     .shortcut = "",
     .help_target = "editing.bond-order",
     .parameter_group = "edit.bond-order",
     .order = 60U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "build.molecule",
     .command_name = "build molecule",
     .menu = "edit",
     .label_source = "Molecule Builder…",
     .status_source = "Build a validated residue, atom, bond, and coordinate fragment",
     .error_source = "The molecular fragment could not be built",
     .keywords_source = "build molecule fragment residue atom bond ligand",
     .unavailable_source = "",
     .shortcut = "",
     .help_target = "editing.molecule-builder",
     .parameter_group = "build.molecule",
     .order = 70U,
     .surfaces = kMenuPanelPalette,
     .requirements = 0U,
     .checkable = false},
    {.id = "trajectory.attach",
     .command_name = "traj load",
     .menu = "trajectory",
     .label_source = "Attach Trajectory",
     .status_source = "Attach a molecular dynamics trajectory to the active topology",
     .error_source = "The trajectory could not be attached",
     .keywords_source = "attach trajectory dynamics frames dcd xtc trr",
     .unavailable_source = "Open a molecular topology before attaching a trajectory",
     .shortcut = "",
     .help_target = "trajectory.attachment",
     .parameter_group = "trajectory.attach",
     .order = 10U,
     .surfaces = kMenuToolbarPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "tools.run-script",
     .command_name = "script run",
     .menu = "tools",
     .label_source = "Run Script",
     .status_source = "Choose and explicitly approve a local Python script",
     .error_source = "The Python script could not be run",
     .keywords_source = "run script python automation",
     .unavailable_source = "",
     .shortcut = "",
     .help_target = "automation.local-script",
     .parameter_group = "tools.run-script",
     .order = 10U,
     .surfaces = kMenuPalette,
     .requirements = 0U,
     .checkable = false},
    {.id = "represent.lines",
     .command_name = "show",
     .menu = "represent",
     .label_source = "Lines",
     .status_source = "Show the active molecular object as lines",
     .error_source = "The lines representation could not be applied",
     .keywords_source = "represent lines wire bonds",
     .unavailable_source = "Open a molecular structure before changing representation",
     .shortcut = "",
     .help_target = "representation.lines",
     .parameter_group = "represent.lines",
     .order = 10U,
     .surfaces = kMenuToolbarPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = true},
    {.id = "represent.sticks",
     .command_name = "show",
     .menu = "represent",
     .label_source = "Sticks",
     .status_source = "Show the active molecular object as sticks",
     .error_source = "The sticks representation could not be applied",
     .keywords_source = "represent sticks bonds cylinders",
     .unavailable_source = "Open a molecular structure before changing representation",
     .shortcut = "",
     .help_target = "representation.sticks",
     .parameter_group = "represent.sticks",
     .order = 20U,
     .surfaces = kMenuToolbarPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = true},
    {.id = "represent.spheres",
     .command_name = "show",
     .menu = "represent",
     .label_source = "Spheres",
     .status_source = "Show the active molecular object as space-filling spheres",
     .error_source = "The spheres representation could not be applied",
     .keywords_source = "represent spheres spacefill cpk atoms",
     .unavailable_source = "Open a molecular structure before changing representation",
     .shortcut = "",
     .help_target = "representation.spheres",
     .parameter_group = "represent.spheres",
     .order = 30U,
     .surfaces = kMenuToolbarPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = true},
    {.id = "represent.ribbon",
     .command_name = "show",
     .menu = "represent",
     .label_source = "Ribbon",
     .status_source = "Show protein secondary structure as a ribbon",
     .error_source = "The ribbon representation could not be applied",
     .keywords_source = "represent ribbon protein secondary structure",
     .unavailable_source = "Open a molecular structure before changing representation",
     .shortcut = "",
     .help_target = "representation.ribbon",
     .parameter_group = "represent.ribbon",
     .order = 40U,
     .surfaces = kMenuPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = true},
    {.id = "represent.cartoon",
     .command_name = "show",
     .menu = "represent",
     .label_source = "Cartoon",
     .status_source = "Show protein secondary structure as a cartoon",
     .error_source = "The cartoon representation could not be applied",
     .keywords_source = "represent cartoon protein secondary structure",
     .unavailable_source = "Open a molecular structure before changing representation",
     .shortcut = "",
     .help_target = "representation.cartoon",
     .parameter_group = "represent.cartoon",
     .order = 50U,
     .surfaces = kMenuToolbarPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = true},
    {.id = "represent.surface",
     .command_name = "surface show",
     .alternate_command_name = "surface hide",
     .menu = "represent",
     .label_source = "Molecular Surface",
     .status_source = "Create a bounded molecular VDW or solvent-accessible surface",
     .error_source = "The molecular surface could not be created",
     .keywords_source = "represent molecular surface vdw sas solvent accessible",
     .unavailable_source = "Open a molecular structure before creating a surface",
     .shortcut = "",
     .help_target = "representation.molecular-surface",
     .parameter_group = "represent.surface",
     .order = 55U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = true},
    {.id = "represent.settings",
     .command_name = "setting list",
     .menu = "represent",
     .label_source = "Render Settings",
     .status_source = "Open the typed render settings editor",
     .error_source = "The render settings editor could not be opened",
     .keywords_source = "render settings style color size quality",
     .unavailable_source = "",
     .shortcut = "",
     .help_target = "render.settings",
     .parameter_group = "represent.settings",
     .order = 60U,
     .surfaces = kMenuPanelPalette,
     .requirements = 0U,
     .checkable = false},
    {.id = "represent.volume-slice",
     .command_name = "volume slice",
     .menu = "represent",
     .label_source = "Volume Slice",
     .status_source = "Show an orthogonal color-mapped scalar volume slice",
     .error_source = "The scalar volume slice could not be created",
     .keywords_source = "represent volume slice scalar map x y z",
     .unavailable_source = "Open a scalar volume before creating a slice",
     .shortcut = "",
     .help_target = "representation.volume-slice",
     .parameter_group = "represent.volume-slice",
     .order = 65U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::volume),
     .checkable = false},
    {.id = "represent.volume-render",
     .command_name = "volume render",
     .alternate_command_name = "volume hide",
     .menu = "represent",
     .label_source = "Direct Volume",
     .status_source = "Render a scalar volume with a versioned transfer function",
     .error_source = "The direct-volume representation could not be created",
     .keywords_source = "represent direct volume ray march transfer ramp density",
     .unavailable_source = "Open a scalar volume before direct rendering",
     .shortcut = "",
     .help_target = "representation.direct-volume",
     .parameter_group = "represent.volume-render",
     .order = 66U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::volume),
     .checkable = true},
    {.id = "analyze.open-panel",
     .command_name = "analyze center",
     .menu = "analyze",
     .label_source = "Analyze",
     .status_source = "Open molecular and trajectory analysis tools",
     .error_source = "The analysis tools could not be opened",
     .keywords_source = "analyze measure center distance contacts rmsd",
     .unavailable_source = "Open a molecular structure before running analysis",
     .shortcut = "",
     .help_target = "analysis.panel",
     .parameter_group = "analyze.panel",
     .order = 10U,
     .surfaces = kMenuToolbarPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "scene.views",
     .command_name = "view list",
     .menu = "scene",
     .label_source = "Views",
     .status_source = "Open camera, projection, stereo, clipping, and named views",
     .error_source = "The scene views could not be opened",
     .keywords_source = "scene views camera projection stereo clipping",
     .unavailable_source = "Open a molecular structure before editing the scene",
     .shortcut = "",
     .help_target = "scene.views",
     .parameter_group = "scene.views",
     .order = 10U,
     .surfaces = kMenuToolbarPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "scene.named-scenes",
     .command_name = "scene list",
     .menu = "scene",
     .label_source = "Named Scenes & Movie",
     .status_source = "Store full-state scenes and build a typed movie track",
     .error_source = "Named scenes and movie tools could not be opened",
     .keywords_source = "scene snapshot state movie timeline keyframe",
     .unavailable_source = "Open a molecular structure before storing a scene",
     .shortcut = "",
     .help_target = "scene.named-scenes",
     .parameter_group = "scene.session-movie",
     .order = 20U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "scene.movie",
     .command_name = "movie status",
     .menu = "scene",
     .label_source = "Movie Timeline",
     .status_source = "Configure typed scene and trajectory keyframes",
     .error_source = "The movie timeline could not be opened",
     .keywords_source = "movie timeline keyframe play seek scene trajectory",
     .unavailable_source = "Open a molecular structure before creating a movie",
     .shortcut = "",
     .help_target = "scene.movie",
     .parameter_group = "scene.session-movie",
     .order = 30U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "help.system-information",
     .command_name = "system info",
     .menu = "help",
     .label_source = "System Information",
     .status_source = "Show runtime, graphics, and support diagnostics",
     .error_source = "System information could not be collected",
     .keywords_source = "help system information diagnostics graphics support",
     .unavailable_source = "",
     .shortcut = "",
     .help_target = "support.system-information",
     .parameter_group = "help.system-information",
     .order = 10U,
     .surfaces = kMenuPanelPalette,
     .requirements = 0U,
     .checkable = false},
    {.id = "object.panel",
     .command_name = "object list",
     .menu = "object",
     .label_source = "Objects",
     .status_source = "Focus the loaded molecular object list",
     .error_source = "The molecular object list could not be focused",
     .keywords_source = "object list manage activate visibility",
     .unavailable_source = "Open a molecular structure to inspect objects",
     .shortcut = "",
     .help_target = "objects.panel",
     .parameter_group = "object.panel",
     .order = 10U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "object.chemistry",
     .command_name = "object chemistry",
     .menu = "object",
     .label_source = "Chemical Semantics",
     .status_source = "Inspect normalized atom and bond chemistry",
     .error_source = "Chemical semantics could not be inspected",
     .keywords_source = "object chemistry charge isotope radical stereo bond",
     .unavailable_source = "Open a molecular structure to inspect chemistry",
     .shortcut = "",
     .help_target = "objects.chemical-semantics",
     .parameter_group = "object.chemistry",
     .order = 20U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "select.expression",
     .command_name = "select",
     .menu = "select",
     .label_source = "Select by Expression",
     .status_source = "Create or replace a named selection from an expression",
     .error_source = "The selection expression could not be applied",
     .keywords_source = "select expression named dynamic atoms query",
     .unavailable_source = "Open a molecular structure before defining a selection",
     .shortcut = "",
     .help_target = "selection.expression",
     .parameter_group = "select.expression",
     .order = 10U,
     .surfaces = kMenuPanelPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "select.all",
     .command_name = "select",
     .menu = "select",
     .label_source = "Select All",
     .status_source = "Create or replace the all-atoms named selection",
     .error_source = "All atoms could not be selected",
     .keywords_source = "select all atoms selection",
     .unavailable_source = "Open a molecular structure before selecting atoms",
     .shortcut = "standard.select-all",
     .help_target = "selection.all",
     .parameter_group = "select.all",
     .order = 20U,
     .surfaces = kMenuContextPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "trajectory.play-pause",
     .command_name = "traj play",
     .alternate_command_name = "traj pause",
     .menu = "trajectory",
     .label_source = "Play / Pause",
     .status_source = "Toggle molecular dynamics trajectory playback",
     .error_source = "Trajectory playback could not be changed",
     .keywords_source = "trajectory play pause animation frames",
     .unavailable_source = "Attach a trajectory before starting playback",
     .shortcut = "standard.media-toggle-play-pause",
     .help_target = "trajectory.playback",
     .parameter_group = "trajectory.play-pause",
     .order = 20U,
     .surfaces = kMenuPanelContextPalette,
     .requirements = requirement_mask(ActionRequirement::trajectory),
     .checkable = true},
    {.id = "represent.show",
     .command_name = "show",
     .menu = "represent",
     .label_source = "Show",
     .status_source = "Show the current representation for all atoms",
     .error_source = "The current representation could not be shown",
     .keywords_source = "represent show reveal visible all atoms",
     .unavailable_source = "Open a molecular structure before changing visibility",
     .shortcut = "",
     .help_target = "representation.visibility",
     .parameter_group = "represent.visibility",
     .order = 70U,
     .surfaces = kMenuContextPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "represent.hide",
     .command_name = "hide",
     .menu = "represent",
     .label_source = "Hide",
     .status_source = "Hide the current representation for all atoms",
     .error_source = "The current representation could not be hidden",
     .keywords_source = "represent hide conceal invisible all atoms",
     .unavailable_source = "Open a molecular structure before changing visibility",
     .shortcut = "",
     .help_target = "representation.visibility",
     .parameter_group = "represent.visibility",
     .order = 80U,
     .surfaces = kMenuContextPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "represent.as",
     .command_name = "as",
     .menu = "represent",
     .label_source = "Show Only",
     .status_source = "Show only the current representation for all atoms",
     .error_source = "The exclusive representation could not be applied",
     .keywords_source = "represent as only exclusive replace all atoms",
     .unavailable_source = "Open a molecular structure before changing visibility",
     .shortcut = "",
     .help_target = "representation.visibility",
     .parameter_group = "represent.visibility",
     .order = 90U,
     .surfaces = kMenuContextPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
    {.id = "represent.toggle",
     .command_name = "toggle",
     .menu = "represent",
     .label_source = "Toggle Visibility",
     .status_source = "Toggle the current representation for all atoms",
     .error_source = "The representation visibility could not be toggled",
     .keywords_source = "represent toggle visibility switch all atoms",
     .unavailable_source = "Open a molecular structure before changing visibility",
     .shortcut = "",
     .help_target = "representation.visibility",
     .parameter_group = "represent.visibility",
     .order = 100U,
     .surfaces = kMenuContextPalette,
     .requirements = requirement_mask(ActionRequirement::workspace),
     .checkable = false},
}};

bool valid_identifier(std::string_view value, bool allow_dot) {
  if (value.empty()) return false;
  return std::all_of(value.begin(), value.end(), [allow_dot](char character) {
    const auto byte = static_cast<unsigned char>(character);
    return std::islower(byte) != 0 || std::isdigit(byte) != 0 ||
           character == '-' || character == '_' ||
           (allow_dot && character == '.');
  });
}

}  // namespace

std::span<const ActionMetadata> default_action_catalog() { return kActions; }

const ActionMetadata* find_action_metadata(std::string_view id) {
  const auto found = std::ranges::find(kActions, id, &ActionMetadata::id);
  return found == kActions.end() ? nullptr : &*found;
}

bool validate_action_catalog(std::span<const ActionMetadata> actions,
                             std::string* error) {
  const auto fail = [error](std::string message) {
    if (error != nullptr) *error = std::move(message);
    return false;
  };
  std::set<std::string_view> identifiers;
  std::set<std::tuple<std::string_view, std::uint16_t>> menu_positions;
  constexpr auto known_surfaces = surface_mask(ActionSurface::menu) |
                                  surface_mask(ActionSurface::toolbar) |
                                  surface_mask(ActionSurface::command_palette) |
                                  surface_mask(ActionSurface::panel) |
                                  surface_mask(ActionSurface::context_menu);
  for (const auto& action : actions) {
    if (!valid_identifier(action.id, true))
      return fail("invalid action id: " + std::string{action.id});
    if (!valid_identifier(action.menu, false))
      return fail("invalid action menu: " + std::string{action.menu});
    if (action.command_name.empty() || action.label_source.empty() ||
        action.status_source.empty() || action.error_source.empty() ||
        action.keywords_source.empty() ||
        action.help_target.empty() || action.parameter_group.empty()) {
      return fail("action metadata contains an empty required field: " +
                  std::string{action.id});
    }
    if (action.requirements != 0U && action.unavailable_source.empty())
      return fail("required action has no unavailable reason: " +
                  std::string{action.id});
    if (!action.alternate_command_name.empty() && !action.checkable) {
      return fail("alternate command requires checkable action: " +
                  std::string{action.id});
    }
    if (action.surfaces == 0U || (action.surfaces & ~known_surfaces) != 0U)
      return fail("invalid action surfaces: " + std::string{action.id});
    if ((action.surfaces &
         surface_mask(ActionSurface::command_palette)) == 0U) {
      return fail("searchable action is missing command-palette surface: " +
                  std::string{action.id});
    }
    if (!identifiers.insert(action.id).second)
      return fail("duplicate action id: " + std::string{action.id});
    if ((action.surfaces & surface_mask(ActionSurface::menu)) != 0U &&
        !menu_positions.emplace(action.menu, action.order).second) {
      return fail("duplicate menu position: " + std::string{action.menu});
    }
  }
  if (error != nullptr) error->clear();
  return true;
}

}  // namespace molshredder::gui
