#include "molshredder/io/format_capabilities.hpp"

namespace molshredder::io {

const std::vector<FormatCapability> &format_capabilities() {
  static const std::vector<FormatCapability> capabilities{
      {"pdb",
       "structure",
       {".pdb", ".ent"},
       true,
       true,
       true,
       false,
       true,
       true,
       {"atom_identity", "residue_identity", "element", "formal_charge",
        "coordinates", "presence", "occupancy", "b_factor", "unit_cell",
        "connectivity", "source_metadata"},
       {"fixed_column_pdb_3_3", "unknown_bond_order", "constant_unit_cell",
        "semantic_loss_report", "partial_pdb_3_3_records"},
       "native"},
      {"mmcif",
       "structure",
       {".cif", ".mmcif"},
       true,
       true,
       true,
       true,
       true,
       true,
       {"atom_identity", "residue_identity", "element", "formal_charge",
        "coordinates", "presence", "occupancy", "b_factor", "unit_cell",
        "connectivity", "source_metadata"},
       {"partial_pdbx_dictionary", "single_category_loops",
        "constant_unit_cell", "single_active_object_export",
        "semantic_loss_report"},
       "native"},
      {"bcif",
       "structure",
       {".bcif"},
       true,
       false,
       true,
       true,
       true,
       false,
       {"atom_identity", "residue_identity", "element", "formal_charge",
        "coordinates", "presence", "occupancy", "b_factor", "unit_cell",
        "connectivity", "source_metadata", "column_mask"},
       {"read_only", "binarycif_0_3_x", "uncompressed_only",
        "pdbx_structure_subset", "in_memory_messagepack"},
       "native_msgpack"},
      {"opendx",
       "volume",
       {".dx"},
       true,
       false,
       false,
       false,
       true,
       false,
       {"scalar_grid", "dimensions", "origin", "delta_vectors",
        "coordinate_unit", "precision", "value_range", "source_metadata"},
       {"read_only", "ascii_regular_grid_only", "single_scalar_field",
        "rank_zero_float_or_double", "in_memory_reader",
        "apbs_default_angstrom", "no_binary_irregular_finite_element"},
       "native"},
      {"mrc",
       "volume",
       {".mrc", ".map", ".ccp4", ".mrcs"},
       true,
       false,
       false,
       false,
       true,
       false,
       {"scalar_grid", "dimensions", "origin", "delta_vectors",
        "coordinate_unit", "precision", "value_range", "axis_permutation",
        "cell_geometry", "extended_header", "source_metadata"},
       {"read_only", "mrc2014_ccp4", "in_memory_reader",
        "scalar_modes_0_1_2_6_12", "complex_modes_unsupported",
        "packed_mode_101_unsupported", "skew_transform_unsupported",
        "handedness_unspecified", "single_grid"},
       "native"},
      {"pqr",
       "structure",
       {".pqr"},
       true,
       true,
       false,
       false,
       true,
       true,
       {"atom_identity", "residue_identity", "inferred_element", "coordinates",
        "partial_charge", "pqr_radius"},
       {"single_frame", "whitespace_delimited", "optional_chain_id",
        "no_explicit_element", "semantic_loss_report"},
       "native"},
      {"mol",
       "structure",
       {".mol"},
       true,
       true,
       false,
       false,
       true,
       true,
       {"element", "coordinates", "connectivity", "bond_order", "formal_charge",
        "isotope", "radical", "atom_properties", "source_metadata"},
       {"v2000_only", "single_structure", "single_frame",
        "query_bonds_unsupported", "bond_stereo_unsupported",
        "semantic_loss_report"},
       "native"},
      {"sdf",
       "structure",
       {".sdf", ".sd"},
       true,
       true,
       false,
       true,
       true,
       true,
       {"element", "coordinates", "connectivity", "bond_order", "formal_charge",
        "isotope", "radical", "atom_properties", "data_fields",
        "source_metadata"},
       {"v2000_only", "single_frame_per_record", "query_bonds_unsupported",
        "bond_stereo_unsupported", "single_active_object_export",
        "semantic_loss_report"},
       "native"},
      {"mol2",
       "structure",
       {".mol2"},
       true,
       true,
       false,
       true,
       true,
       true,
       {"atom_identity", "residue_identity", "sybyl_atom_type", "coordinates",
        "connectivity", "bond_order", "amide_bond", "partial_charge",
        "charge_presence", "atom_status", "unit_cell", "source_metadata"},
       {"single_frame_per_molecule", "dummy_query_bonds_unsupported",
        "requires_explicit_atom_type_for_write", "single_active_object_export",
        "semantic_loss_report"},
       "native"},
      {"psf",
       "structure",
       {".psf"},
       true,
       true,
       false,
       false,
       true,
       true,
       {"atom_identity", "residue_identity", "segment_identity",
        "inferred_element", "force_field_atom_type", "partial_charge", "mass",
        "connectivity", "angles", "dihedrals", "impropers", "term_multiplicity",
        "topology_only", "source_metadata"},
       {"no_coordinates", "standard_namd_ext_xplor", "unknown_bond_order",
        "cmap_drude_cheq_unsupported", "auxiliary_sections_not_modeled",
        "requires_force_field_properties_for_write", "semantic_loss_report"},
       "native"},
      {"prmtop",
       "structure",
       {".prmtop", ".parm7", ".top"},
       true,
       false,
       false,
       false,
       true,
       true,
       {"atom_identity", "residue_identity", "atomic_number",
        "force_field_atom_type", "atom_type_index", "partial_charge", "mass",
        "connectivity", "angles", "dihedrals", "impropers", "term_multiplicity",
        "gb_radius", "gb_screen", "unit_cell_template", "topology_only",
        "source_metadata"},
       {"read_only", "standard_amber_only", "chamber_unsupported",
        "perturbation_unsupported", "force_parameter_arrays_not_modeled",
        "no_coordinates"},
       "native"},
      {"gro",
       "structure",
       {".gro"},
       true,
       true,
       true,
       false,
       true,
       true,
       {"atom_identity", "residue_identity", "inferred_element", "coordinates",
        "velocity", "physical_time", "unit_cell", "frame_title"},
       {"stable_atom_order", "fixed_width_identity", "five_character_names",
        "no_connectivity", "in_memory_reader", "semantic_loss_report"},
       "native"},
      {"g96",
       "structure",
       {".g96"},
       true,
       true,
       true,
       false,
       true,
       true,
       {"atom_identity", "residue_identity", "inferred_element", "coordinates",
        "velocity", "source_step", "physical_time", "unit_cell", "frame_blocks",
        "source_metadata"},
       {"stable_atom_order", "fixed_f15_9", "five_character_names",
        "full_or_reduced_blocks", "no_connectivity", "in_memory_reader",
        "semantic_loss_report"},
       "native"},
      {"vtf",
       "structure",
       {".vtf"},
       true,
       false,
       true,
       false,
       true,
       true,
       {"atom_identity", "residue_identity", "atomic_number", "atom_type",
        "partial_charge", "mass", "vdw_radius", "occupancy", "b_factor",
        "connectivity", "coordinates", "unit_cell",
        "sparse_coordinate_inheritance"},
       {"read_only", "vtf_combined_only", "no_vsf_vcf_pairing",
        "unknown_bond_order", "in_memory_reader", "no_timestep_time"},
       "native"},
      {"xyz",
       "structure",
       {".xyz"},
       true,
       true,
       true,
       false,
       true,
       true,
       {"element", "coordinates", "frame_comment"},
       {"plain_xyz_only", "stable_atom_order", "angstrom_output",
        "semantic_loss_report"},
       "native"},
      {"dcd",
       "trajectory",
       {".dcd"},
       true,
       false,
       true,
       false,
       true,
       true,
       {"coordinates", "source_step", "unit_cell", "precision"},
       {"read_only", "known_atom_count_required",
        "fixed_atom_subset_unsupported"},
       "native_indexed"},
      {"trr",
       "trajectory",
       {".trr"},
       true,
       false,
       true,
       false,
       true,
       true,
       {"coordinates", "velocity", "force", "source_step", "physical_time",
        "unit_cell", "precision"},
       {"read_only", "known_atom_count_required"},
       "native_indexed_xdr"},
      {"xtc",
       "trajectory",
       {".xtc"},
       true,
       false,
       true,
       false,
       true,
       true,
       {"coordinates", "source_step", "physical_time", "unit_cell",
        "compression_precision"},
       {"read_only", "known_atom_count_required", "1995_format_atom_limit"},
       "native_indexed_xdr"},
      {"mdcrd",
       "trajectory",
       {".mdcrd", ".crd"},
       true,
       false,
       true,
       false,
       true,
       true,
       {"coordinates", "unit_cell", "precision", "frame_title"},
       {"read_only", "known_atom_count_required", "fixed_width_f8",
        "no_step_or_time", "no_velocity_or_force", "remd_header_unsupported",
        "small_system_box_ambiguity"},
       "native_indexed_ascii"},
      {"lammps",
       "trajectory",
       {".lammpstrj", ".lammpstraj", ".dump"},
       true,
       false,
       true,
       false,
       true,
       true,
       {"coordinates", "source_step", "unit_cell", "atom_id",
        "frame_atom_properties", "box_origin", "boundary"},
       {"read_only", "known_atom_ids_required", "coordinate_unit_required",
        "orthogonal_or_restricted_triclinic", "general_triclinic_unsupported",
        "one_coordinate_triplet_per_snapshot", "text_dump_only"},
       "native_indexed_ascii"},
      {"netcdf",
       "trajectory",
       {".nc", ".ncdf", ".netcdf"},
       true,
       false,
       true,
       false,
       true,
       true,
       {"coordinates", "velocity", "force", "physical_time", "temperature",
        "unit_cell", "precision", "scale_factor", "integer_compression",
        "storage_format"},
       {"read_only", "amber_convention_1_0", "known_atom_count_required",
        "full_3d_unit_cell_only", "remd_metadata_not_exposed",
        "netcdf_c_runtime_dependency"},
       "native_random_access_netcdf_c"},
      {"h5md",
       "trajectory",
       {".h5md"},
       true,
       false,
       true,
       false,
       true,
       true,
       {"coordinates", "velocity", "force", "source_step", "physical_time",
        "unit_cell", "particle_id", "presence", "mass", "charge", "species",
        "image", "precision", "si_units", "particle_group"},
       {"read_only", "h5md_1_x", "three_dimensions_only",
        "topology_source_ids_required_for_non_index_ids",
        "missing_position_unit_requires_override",
        "partial_periodic_boundary_unsupported",
        "arbitrary_observables_not_exposed", "external_storage_rejected",
        "hdf5_runtime_dependency"},
       "native_random_access_hdf5_c"},
      {"binpos",
       "trajectory",
       {".binpos"},
       true,
       false,
       true,
       false,
       true,
       true,
       {"coordinates", "precision", "byte_order"},
       {"read_only", "known_atom_count_required", "float32_coordinates",
        "no_unit_cell", "no_step_or_time", "no_velocity_or_force",
        "native_endian_legacy_format", "uncompressed_only"},
       "native_indexed_binary"},
      {"rst7",
       "trajectory",
       {".rst7", ".restrt", ".inpcrd", ".inprst"},
       true,
       false,
       false,
       false,
       true,
       true,
       {"coordinates", "velocity", "physical_time", "temperature", "unit_cell",
        "source_metadata"},
       {"read_only", "single_frame", "known_atom_count_required_for_attach",
        "in_memory_reader", "small_system_optional_block_ambiguity"},
       "native"},
  };
  return capabilities;
}

} // namespace molshredder::io
